### LOCAL SETTINGS
### --------------
### Sketch depending settings, mostly the same but libs not.

### Usually can be auto-detected from the sketch.
ARDUINO_SKETCHBOOK = ./
ARDUINO_LIBS = Arduino-IRremote

BOARD_TAG = atmega328
MONITOR_PORT = /dev/ttyUSB0

### GLOBAL SETTINGS
### ---------------

### Path of your Arduino-Makefile folder
ARDMK_DIR = ../Arduino-Makefile
include $(ARDMK_DIR)/Arduino.mk
